name: Build Godot Extension (Linux)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Automatically initializes and updates submodules

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential scons python3 python3-pip

    - name: Build Godot C++ Bindings
      run: |
        cd godot-cpp
        scons platform=linux
        cd ..

    - name: Run Build Script
      run: |
        scons platform=linux

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-libraries
        path: build/bin/
